x-api: &api
  restart: always
  environment:
    - ASPNETCORE_ENVIRONMENT=Production
  networks:
    - labaspapi_0_network
  stop_grace_period: 10s
#--------------------------------------------------
services:
  labaspapi_0_nginx:
    restart: always
    image: nginx:latest
    container_name: labaspapi_0_nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./log/nginx:/var/log/nginx
    networks:
      - labaspapi_0_network
#--------------------------------------------------
  labaspapi_blue:
    <<: *api
    build:
      context: ./LabAspApi
    image: labaspapi:blue
    container_name: labaspapi_blue

  labaspapi_green:
    <<: *api
    build:
      context: ./LabAspApi
    image: labaspapi:green
    container_name: labaspapi_green
#--------------------------------------------------
  labaspapi_aaaa_blue:
    <<: *api
    build:
      context: ./LabAspApi_AAAA
    image: labaspapi_aaaa:blue
    container_name: labaspapi_aaaa_blue

  labaspapi_aaaa_green:
    <<: *api
    build:
      context: ./LabAspApi_AAAA
    image: labaspapi_aaaa:green
    container_name: labaspapi_aaaa_green
#--------------------------------------------------
  labaspapi_bbbb_blue:
    <<: *api
    build:
      context: ./LabAspApi_BBBB
    image: labaspapi_bbbb:blue
    container_name: labaspapi_bbbb_blue

  labaspapi_bbbb_green:
    <<: *api
    build:
      context: ./LabAspApi_BBBB
    image: labaspapi_bbbb:green
    container_name: labaspapi_bbbb_green
#--------------------------------------------------
  labaspapi_cccc_blue:
    <<: *api
    build:
      context: ./LabAspApi_CCCC
    image: labaspapi_cccc:blue
    container_name: labaspapi_cccc_blue

  labaspapi_cccc_green:
    <<: *api
    build:
      context: ./LabAspApi_CCCC
    image: labaspapi_cccc:green
    container_name: labaspapi_cccc_green
#--------------------------------------------------
networks:
  labaspapi_0_network:
    driver: bridge
