x-log: &log
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
#--------------------------------------------------
networks:
  labaspapi_0_network:
    driver: bridge
#--------------------------------------------------
x-api: &api
  <<: *log
  restart: always
  environment:
    - ASPNETCORE_ENVIRONMENT=Production
  networks:
    - labaspapi_0_network
  stop_grace_period: 10s
#--------------------------------------------------
services:
  labaspapi_0_nginx:
    <<: *log
    restart: always
    image: nginx:latest
    container_name: labaspapi_0_nginx
    ports:
      - "10100:80" # 외부:내부(호스트 포트:컨테이너[nginx] 내부 포트). 내부 포트는 nginx.conf 의 listen 포트와 같도록 설정
      - "10110:443"
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./log/nginx:/var/log/nginx
      - C:/specter/ssl/svwln/svwln.crt:/usr/share/svwln/svwln.crt:ro
      - C:/specter/ssl/svwln/svwln.key:/usr/share/svwln/svwln.key:ro
    networks:
      - labaspapi_0_network
#--------------------------------------------------
x-labaspapi_db: &labaspapi_db
  environment:
    - ConnectionStrings__DefaultConnection=${labaspapi_db}

  labaspapi_blue:
    <<: *api
    <<: *labaspapi_db
    build:
      context: ./LabAspApi
    image: labaspapi:blue
    container_name: labaspapi_blue

  labaspapi_green:
    <<: *api
    <<: *labaspapi_db
    build:
      context: ./LabAspApi
    image: labaspapi:green
    container_name: labaspapi_green
#--------------------------------------------------
x-labaspapi_aaaa_db: &labaspapi_aaaa_db
  environment:
    - ConnectionStrings__DefaultConnection=${labaspapi_aaaa_db}

  labaspapi_aaaa_blue:
    <<: *api
    <<: *labaspapi_aaaa_db
    build:
      context: ./LabAspApi_AAAA
    image: labaspapi_aaaa:blue
    container_name: labaspapi_aaaa_blue

  labaspapi_aaaa_green:
    <<: *api
    <<: *labaspapi_aaaa_db
    build:
      context: ./LabAspApi_AAAA
    image: labaspapi_aaaa:green
    container_name: labaspapi_aaaa_green
#--------------------------------------------------
  labaspapi_bbbb_blue:
    <<: *api
    build:
      context: ./LabAspApi_BBBB
    image: labaspapi_bbbb:blue
    container_name: labaspapi_bbbb_blue

  labaspapi_bbbb_green:
    <<: *api
    build:
      context: ./LabAspApi_BBBB
    image: labaspapi_bbbb:green
    container_name: labaspapi_bbbb_green
#--------------------------------------------------
  labaspapi_cccc_blue:
    <<: *api
    build:
      context: ./LabAspApi_CCCC
    image: labaspapi_cccc:blue
    container_name: labaspapi_cccc_blue

  labaspapi_cccc_green:
    <<: *api
    build:
      context: ./LabAspApi_CCCC
    image: labaspapi_cccc:green
    container_name: labaspapi_cccc_green
