name: Lab Actions

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "2pectre"
          git config --global user.email "2pectre@users.noreply.github.com"
        shell: powershell

      - name: Find and Run deploy.sh for LabAspApi folders
        run: |
          $baseDir = 'C:\actions-runner\_work\LabAspApi\LabAspApi'
          Get-ChildItem -Path $baseDir -Directory -Filter 'LabAspApi_*' | ForEach-Object {
            $deployScript = "$_.\deploy.sh"
            if (Test-Path $deployScript) {
              Write-Output "Running deploy script in $($_.FullName)"
              Push-Location $_.FullName
              & "C:\Program Files\Git\bin\bash.exe" $deployScript
              Pop-Location
            } else {
              Write-Output "No deploy.sh found in $($_.FullName)"
            }
          }
        shell: powershell
