name: Lab Actions

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "2pectre"
          git config --global user.email "2pectre@users.noreply.github.com"
        shell: powershell

      - name: Find LabAspApi folders
        id: find-folders
        run: |
          $rootPath = "${{ github.workspace }}"
          $folders = Get-ChildItem -Directory -Path $rootPath | Where-Object { $_.Name -match '^LabAspApi_[\w]+$' }
          $validFolders = @()
          foreach ($folder in $folders) {
            if (Test-Path "$($folder.FullName)\deploy.sh") {
              $validFolders += $folder.Name
            }
          }
          $outputPath = "${{ github.env }}"
          Add-Content $outputPath "FOLDERS=$($validFolders -join ',')"
        shell: powershell

      - name: Deploy scripts
        run: |
          $folders = $Env:FOLDERS.Split(',')
          foreach ($folder in $folders) {
            $deployPath = "$Env:GITHUB_WORKSPACE\$folder\deploy.sh"
            $deployDir = Split-Path -Parent $deployPath
            Push-Location $deployDir
            & "C:\Program Files\Git\bin\bash.exe" "./deploy.sh"
            Pop-Location
          }
        shell: powershell
        env:
          FOLDERS: ${{ steps.find-folders.outputs.FOLDERS }}
