name: Lab Actions

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "2pectre"
          git config --global user.email "2pectre@users.noreply.github.com"
        shell: powershell

      - name: Run deploy.sh for dynamically detected folders
        run: |
          $baseDir = "$env:GITHUB_WORKSPACE"
          Get-ChildItem -Path $baseDir -Directory -Filter "LabAspApi_*" | ForEach-Object {
            $folderPath = $_.FullName
            $deployScript = Join-Path $folderPath "deploy.sh"

            if (Test-Path $deployScript) {
              Write-Host "Running deploy.sh in $folderPath"
              & "C:\Program Files\Git\bin\bash.exe" $deployScript
            } else {
              Write-Host "deploy.sh not found in $folderPath, skipping."
            }
          }
        shell: powershell
