name: Lab Actions

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "2pectre"
          git config --global user.email "2pectre@users.noreply.github.com"
        shell: powershell

      - name: Run deploy.sh for LabAspApi_0
        working-directory: LabAspApi_0
        run: |
<<<<<<< Updated upstream
          $rootDir = 'C:\actions-runner\_work\LabAspApi\LabAspApi'
          $folders = Get-ChildItem -Path $rootDir -Directory | Where-Object { $_.Name -match '^LabAspApi_\d+$' }
          foreach ($folder in $folders) {
            $deployScript = "$($folder.FullName)\deploy.sh"
            if (Test-Path $deployScript) {
              & "C:\Program Files\Git\bin\bash.exe" $deployScript
            }
          }
=======
          & "C:\Program Files\Git\bin\bash.exe" ./deploy.sh
        shell: powershell

      - name: Run deploy.sh for LabAspApi_1
        working-directory: LabAspApi_1
        run: |
          & "C:\Program Files\Git\bin\bash.exe" ./deploy.sh
        shell: powershell

      - name: Run deploy.sh for LabAspApi_2
        working-directory: LabAspApi_2
        run: |
          & "C:\Program Files\Git\bin\bash.exe" ./deploy.sh
>>>>>>> Stashed changes
        shell: powershell
